# Python code to demonstrate the Exception of
# randrange(), ValueError, Float value

import random

# Using randrange() to generate numbers from 14.5-100
# Raises Exception
print ("Random number from 14.5-100 is : ",end="")
print (random.randrange(14.5,100))
