# Python code to demonstrate the Exception of
# randrange(), ValueError, start >= start

import random

# Using randrange() to generate numbers from 500-100
# Raises Exception
print ("Random number from 500-100 is : ",end="")
print (random.randrange(500,100))
