# this will generate an error.
df2_grouped.reset_index()
